language: node_js
node_js:
  - "7.8.0"
before_install:
  - "npm install -g polymer-cli bower"
  - "bower install"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
addons:
  firefox: "latest"
  apt:
    packages:
      - oracle-java8-set-default
script:
  - "polymer test -l \"firefox\""